### PR TITLE
[TMVA] Clean-up cross-validation, add error-handling and example

### PR DESCRIPTION
**Pull request by stwunsch**
Changes:
- Clean-up coding style and add comments
- Add error-handling for the cases
  - No method booked before calling `Evaluate` (`methodName` is empty string, prevents segfault which is hard to interpret for users)
  - No `Evaluate` run before calling `GetResults` (map size of ROCs is zero)

@lmoneta @omazapa Only merge if nobody is currently working on this code! The coding style fixes will make merging horrible ;)

### CODE REVIEW

**Comment by stwunsch** [comment]
Added unbiased estimation of ROC standard deviation to cross-validation results and appended this information to the print function

**Comment by stwunsch** [comment]
Here a test file:

```
#!/usr/bin/env python

from ROOT import TMVA, TFile, TTree, TCut
from subprocess import call
from os.path import isfile

# Setup TMVA
TMVA.Tools.Instance()
TMVA.PyMethodBase.PyInitialize()

# Load data
if not isfile('tmva_class_example.root'):
    call(['curl', '-O', 'http://root.cern.ch/files/tmva_class_example.root'])

data = TFile.Open('tmva_class_example.root')
signal = data.Get('TreeS')
background = data.Get('TreeB')

dataloader = TMVA.DataLoader('dataset')
for branch in signal.GetListOfBranches():
    dataloader.AddVariable(branch.GetName())

dataloader.AddSignalTree(signal, 1.0)
dataloader.AddBackgroundTree(background, 1.0)
dataloader.PrepareTrainingAndTestTree(TCut(''),
        'nTrain_Signal=4000:nTrain_Background=4000:SplitMode=Random:NormMode=NumEvents:!V')

# Setup cross-validation
cv = TMVA.CrossValidation(dataloader)
cv.BookMethod(TMVA.Types.kFisher, 'Fisher', '!H:!V:Fisher')
cv.Evaluate()
results = cv.GetResults()
results.Print()
```

**Comment by stwunsch** [comment]
Added cross validation example in `tutorials/tmva/TMVACrossValidation.C`

**Comment by stwunsch** [comment]
@ThomasStevensonQM Does this PR conflict with work done by you? At the IML meeting, it sounded like you've some uncommitted code somehwere.

**Comment by lmoneta** [comment]
Hi Stefan, it should be fine. 
I was away but I'll commit it today

**Comment by stwunsch** [comment]
Alright, no problem! Thanks :)

**Comment by lmoneta** [comment]
It is now committed in the master and 6.08 branches.
Thank you

**Pull request closed without merging**
