### PR TITLE
Roo stream parser fix

### PR DESCRIPTION
**Pull request by cpviolation**
RooArgSet allows to create a file with the information from the arguments stored in the set with the method RooArgSet::writeToFile(...).
Unfortunately, when using the corresponding RooArgSet::readFromFile function, there is a parsing problems for numbers in the form Xe+YZ, and the information gets lost in the import. The following error is produced:

```
[#0] ERROR:InputArguments -- RooRealVar::readFromStream(x): parse error, cannot convert '1e' to double precision
```
You can test yourself with this script: [root-prob.py](https://root.cern.ch/phpBB3/download/file.php?id=13191&sid=a39a5dc5dc04a4c2be38081286650206).

I’ve tracked the problem down to a forgotten case in RooStreamParser::readToken(). And after fixing it I made the script work as expected ([after.txt](https://root.cern.ch/phpBB3/download/file.php?id=13192&sid=a39a5dc5dc04a4c2be38081286650206)).

Apologies for the trailing whitespace removed. Only real change at line 230.

### CODE REVIEW

**Comment by dpiparo** [comment]
Hi,
thanks a lot for moving the code as a PR to github. I am on this.

**Comment by dpiparo** [comment]
Hi,
I may be doing something wrong here but running the root-prob.py on 8f87cc I do not get any failure :-(
```
RooFit v3.60 -- Developed by Wouter Verkerke and David Kirkby 
                Copyright (C) 2000-2013 NIKHEF, University of California & Stanford University
                All rights reserved, please read http://roofit.sourceforge.net/license.txt

[#1] INFO:ObjectHandling -- RooWorkspace::import(ws) importing RooRealVar::x
x before reading
RooRealVar::x = 10  L(1 - 100) 
x after reading
RooRealVar::x = 10  L(1 - 100) 
```
thoughts?

Cheers,
    Danilo

**Comment by cpviolation** [comment]
Hi,

This is quite strange, since I’ve just tried with the master and I see the error.

```
$ root -v
   -----------------------------------------------------------------
  | Welcome to ROOT 6.09/01                     http://root.cern.ch |
  |                                    (c) 1995-2016, The ROOT Team |
  | Built for macosx64                                              |
  | From heads/master@v6-09-01-1544-gf112562, Feb 17 2017, 10:42:56 |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'      |
   -----------------------------------------------------------------
```
```
$ python root-prob.py 

RooFit v3.60 -- Developed by Wouter Verkerke and David Kirkby 
                Copyright (C) 2000-2013 NIKHEF, University of California & Stanford University
                All rights reserved, please read http://roofit.sourceforge.net/license.txt

[#1] INFO:ObjectHandling -- RooWorkspace::import(ws) importing RooRealVar::x
x before reading
RooRealVar::x = 10  L(1 - 100) 
[#0] ERROR:InputArguments -- RooRealVar::readFromStream(x): parse error, cannot convert '1e' to double precision
x after reading
RooRealVar::x = 100  L(1 - 100) 
```
Anyway, even without the error the behaviour you obtain is not correct, since the script should have produced a `test.txt` file with a single line of the kind
```
x =  1e+06 L(10000 - 1e+06) 
```
and this is not read correctly by RooArgSet::readFromFile()

**Comment by dpiparo** [comment]
Hi,
I'd like to 
- put a test in the testsuite
- reproduce the problem
- merge the pr
- see the problem disappear

unfortunately I am stuck at the first step. Now recompiling at your revision.

**Comment by cpviolation** [comment]
In case it helps, I’ve compiled with the following commands on macosx64:
```
root $ mkdir cmake_build; cd cmake_build
cmake_build $ cmake -DCMAKE_INSTALL_PREFIX=../install -D roofit:BOOL=ON -D minuit2:BOOL=ON -D CMAKE_CXX_FLAGS=-I/usr/local/opt/openssl/include -D CMAKE_LD_FLAGS=-L/usr/local/opt/openssl/lib ../
cmake_build $ make -j8
```

**Comment by dpiparo** [comment]
ok, it works, ehm, fails on osx but not on linux.

**Comment by dpiparo** [comment]
Test added and merged, thanks.

**Pull request closed without merging**
