### PR TITLE
Correct rule generation for builtin libraries.

### PR DESCRIPTION
**Pull request by bbockelm**
The builtin Vdt and Vc builds, when enabled, cause some targets to depend on libraries (`libvdt.so`, `libVc.a`) that are the output of the `ExternalProject` command.  However, unless they are explicitly listed as outputs (as done in this patch), the build tool may not know how to generate them.

Typically, this isn't a problem because the builtins are done sufficiently early in the build and it's nearly impossible to hit the Vc dependency before the library is installed.  `make` is satisfied as long the library is on disk by time it hits the later rule, even if it has no clue how it got there.

However, some build tools (such as `ninja`) explicitly check for missing libraries and refuse to attempt the build because no rule explicitly builds the missing library.

As far as I can tell, the `BUILD_BYPRODUCTS` attribute was added in CMake 3.2; as ROOT already requires 3.4.3, this patch should not be a problem.

@pcanal @karies

### CODE REVIEW

**Comment by peremato** [comment]
Hi Brian. Thanks for your suggestion. I'll have a look at the implications of the BUILD_PRODUCTS, and eventually apply it everywhere. The only concern is that you need to know the a priori what are the libraries and headers produced by building the external. 
Until now we have handled the dependencies by adding the following statements in the package that have a dependence to the builtin libraries:
```
if(builtin_xrootd)
  ROOT_ADD_BUILTIN_DEPENDENCIES(Netx XROOTD)
endif()
```
In this example the target `Netx` depends on the libraries produced by the target `XROOTD`, which is using the `ExternalProject`.

**Comment by bbockelm** [comment]
It looks like `ROOT_ADD_BUILTIN_DEPENDENCIES` only works if the external target name and the library variable name are the same.  I.e., `LZMA` and `LZMA_LIBRARIES`.

However, for `vc`, the target name is `VC` and the library name is `Vc_LIBRARIES`.  Seems that the existing logic in `ROOT_ADD_BUILTIN_DEPENDENCIES` is case sensitive.

**Comment by bbockelm** [comment]
Looking deeper - I think the correct approach would be to remove `ROOT_ADD_BUILTIN_DEPENDENCIES` and just depend on the `BUILD_BYPRODUCTS` attribute.  Reduces a bunch of custom code, making the ROOT build easier to understand (and does a small reduction in the complexity of the build).

**Comment by bbockelm** [comment]
Just pushed a fix that removes `ROOT_ADD_BUILTIN_DEPENDENCIES`.

Note that this branch retains the current race condition in `ROOT_ADD_BUILTIN_DEPENDENCIES`: the external build produces the header files, but the individual source files are not dependent on the outcome of the external build.

For example, `TDavixFile.cxx.o` is in reality dependent on `TDavixFile.cxx` and `davix.hpp`; however, if `davix.hpp` is the output of the `DAVIX` external project, there's no CMake dependency  forcing `DAVIX` to be built before `TDavixFile.cxx.o`.

There *is* a CMake dependency for `libRDAVIX.so` on `DAVIX`.

So, we do the library dependencies correctly but not the header file dependencies.  This was true before this PR and continues to be true.  I'll look into that next.

**Comment by bbockelm** [comment]
Ok, after a bit more investigation into the generated `build.ninja`, scratch the above comment.

It seems inter-target dependencies also cover the source files.  That is, if target `foo` is a dependency of `bar`, then `foo` must be complete before the first source file of `bar` is compiled.

I thus pushed a commit that finishes the cleanup:
* All dependencies are correct.  When a library file is listed as a dependency of something, the project which generates this file has it correctly listed in `BUILD_BYPRODUCTS`.
* Built-in dependencies of an executable or library can be listed in the respective ROOT macro.  Putting it in a macro allows us to skip the redundant `if(builtin_foo)` code blocks.

**Comment by peremato** [comment]
Hi Brian. I like the more elegant way to handle the library/executable dependencies to builtins, which as pointed are still necessary.  I do not known what did we bought with `BUILD_BYPRODUCTS`, specially for the makefile case. My suspicion is that to would work if the ExternalProject macro is used in the same subdirectory that the byproducts are used. In any case, I guess it does not do any damage.  
I have merged your commits to the master as well as some minor changes to keep the treatment uniform for all builtins.

**Pull request closed without merging**
