### PR TITLE
Compression namespace

### PR DESCRIPTION
**Pull request by pseyfert**
* exclude ECompressionAlgorithm from namespace ROOT in C (namespaces are a C++ thing)
* that enables using Compression.h in C
* Bits.h can then use ECompressionAlgorithm instead of hard coded numbers

### CODE REVIEW

**Comment by pcanal** [comment]
Thanks Paul.  This has been merged in the master.

**Comment by karies** [comment]
I am not in love with `ROOT::kUseGlobalSetting`, to say the least :-) It gives no indication of context. Maybe `ROOT::Compression::kGlobalSetting` using an enum class?

Paul - would you mind sending another PR, or do you prefer if we do this?

**Comment by pseyfert** [comment]
I see your point, but if I see it correctly that enum got defined in 2011 and I only resolved the points where hard coded integers instead of the enum were used. Changing the namespace from `ROOT::` to `ROOT::Compression::` would break third party code containing `ROOT::CompressionSettings(ROOT::kLZMA, 1)` or am I missing something?

**Comment by karies** [comment]
Thanks for the explanation! Very unfortunate :-(

**Pull request closed without merging**
