### PR TITLE
[TDF] miscellaneous fixes

### PR DESCRIPTION
**Pull request by bluehood**

### CODE REVIEW

**Comment by peremato** [comment]
@phsft-bot build!

**Comment by dpiparo** [comment]
Everything fine for me in the patch. I particularly appreciate the coming back of shared_from_this.
Let's wait the response of the bot.

**Comment by bluehood** [comment]
Rebased on master

**Comment by martinmine** [comment]
@phsft-bot build!

**Comment by dpiparo** [comment]
Merged, thanks.

**Pull request closed without merging**
