### PR TITLE
Rewrite ROOT::Experimental::TDirectory[Entry].h, add cast to base class

### PR DESCRIPTION
**Pull request by BerserkerTroll**
Based on [1]

[1] Neri, C, "Twisting the RTTI System for Safe Dynamic Casts of void* in C++", Dr.Dobb's Journal, April 05, 2011. http://drdobbs.com/cpp/229401004

### CODE REVIEW

**Comment by karies** [comment]
Thanks! As I said before I'm not in love with this. One of the issues I have - apart from the fact that exceptions are misused here - is that this makes it impossible to use ROOT from -fno-exceptions code.

OTOH, I don't see an alternative without reflection :-( So I'll leave this open for another few days to give me some time to think about it. In the end we have to weigh TClass versus exception "mis-"use...

**Comment by BerserkerTroll** [comment]
@karies 
> exceptions are misused here
Well, it's kinda questionable. If there is a function searching for something in a complex structure using several nested loops and when it finds what it needs, it throws exception Found(result) and catches it outside loops, then we say that "exceptions are misused here". Because there is methods to exit nested loops (`goto`) so exceptions shouldn't be used for control flow.

If not consider implementing own reflection, exceptions are the only way to do what done here. Of course, in ROOT I can't consider it, because there already is own reflection.

> this makes it impossible to use ROOT from -fno-exceptions code
But TDirectory::Get, which throws TDirectoryUnknownKey or TDirectoryTypeMismatch, doesn't make. okay.


A note about `TDirectoryEntry::TClass*` data member. I had to add it, because `TClass::GetClass` wants `std::type_info`, which I couldn't store if I wanted to keep `TDirectoryEntry` copy/move constructible/assignable. So I had to use `std::type_index` member to keep it moveable and `TClass*` member for `TClass* TDirectoryEntry::GetType()` to be used by `TFile::Write()`. But now I think I can get rid of the `TClass*` member because, I believe, there is legit way to extract `const std::type_info&` from `std::type_index`.

**Comment by pcanal** [comment]
What bother me most about the exception solution is that it is relatively speaking very slow ... and thus a solution based on the reflection information that we do have is even more attractive.

**Comment by BerserkerTroll** [comment]
@pcanal I've benchmarked 'throw_cast' (let me call it this way) vs. TClass::DynamicCast. Yes, exceptions are kinda slow (40 times slower, to be precise). Ok, if you have own RTTI, there is no reason not to use it.

But, newertheles, I think original code should be rewritten a bit. There are some flaws and rough edges.
E.g. too much indirection (virtual methods, returning pointer to `PtrBase`), `TDirectory` claims to have shared ownership, but `PtrBase` doesn't reflect this in its interface. `GetPointer`, returning raw pointer (user might catch  it into smart ptr and then bad things will happen). Some inconsistences in types (somewhere they are modified with `ToContentType_t<T>`, somewhere there is raw `T`). And so on.

**Comment by karies** [comment]
As discussed we'd /love/ to see this PR's refactoring (minus the exceptions) in a new PR; basically to leave this PR as a historical marker should we ever change our mind wrt exceptions.

Thanks & looking forward to the refactoring PR, it's *much* nicer!

**Pull request closed without merging**
