### PR TITLE
Comments and refactorings (hidden -> masked) in the TextInput.

### PR DESCRIPTION
**Pull request by perovic**
Passes cling test and roottest.

### CODE REVIEW

**Comment by karies** [comment]
Thanks!

Do we also need changes in the Windows part?

**Comment by perovic** [comment]
Not for now, code changes were only made in the platform-agnostic part.

**Comment by karies** [comment]
Awesome, thanks SO much!

Merged (after squash)!

**Comment by perovic** [comment]
My pleasure :+1: 
On to the next one!

**Pull request closed without merging**
