### PR TITLE
Initial python command line interface to TSimpleAnalysis.

### PR DESCRIPTION
**Pull request by lgiommi**

### CODE REVIEW

**Comment by dpiparo** [comment]
Hi Luca,

nice job. Some comments about aspects that need improving before merging, namely all of the following items with equal priority:
1) Remove all variable names in Italian language
2) The help of the individual switches for the command line is there to be helpful. Please take some time to write proper text there, for example avoiding contentless tautologies like "inputFile is the input file"
3) The script is missing a description to be prompted when the user requires help with the -h switch. This description does not need to be a long text but a short synopsis of the utility. Adding example invocations would greatly increase its usefulness.
4) You do not need to parse the header. I saw you now have a dictionary for the class. The autoloating and autoparsing will kick in and provide the ROOT typesystem with the necessary info. The direct usage of RunSumpleAnalysis should be discarded in favour of an explicit instantiation of a TSimpleAnalysis object (ROOT cannot autoload based on free function names)
5) "Invalid argument set" shall be printed on stderr
6) The script must be compatible python2 and python3, e.g. for what concerns the print function
7) The deciding factor for invoking the constructor with only the configuration file or the separate arguments is the presence of the "inputfile". The rest of the checks are not useful. One should rather make very clear in the documentation of the switches that the priority is given to the config file and perhaps print in case both a config and other parameters are present a warning about the non-config parameters being ignored.

Cheers,
    Danilo

**Comment by lgiommi** [comment]
Thank you Danilo for reply. I hope that now the code is better.
Luca

**Comment by dpiparo** [comment]
Merged. Thanks.

**Comment by dpiparo** [comment]
Are the tests for it in a PR for roottest?

**Comment by karies** [comment]
In my inbox for now; Luca is improving it. One of us will create a PR soon-ish.

**Pull request closed without merging**
