### PR TITLE
adding in ability for rooteventselector to skim trees based on a selection string

### PR DESCRIPTION
**Pull request by lawrenceleejr**
Hi all,

I love the new command line utils included in the releases in root/main/python/.

However, I found the rooteventselector command to be lacking in some functionality, so I added the ability for it to skim based on a selection string (a la a TCut). I hope this is useful for others!

-Larry

### CODE REVIEW

**Comment by dpiparo** [comment]
Hi Larry,

nice new feature: thanks for providing it!
Before merging, I'd have some comments:
  - Could the operation of cutting take place only if a non-empty selection string is provided?
  - Can the variable smalltree not be reused?

Cheers,
D

**Comment by lawrenceleejr** [comment]
Hi, Thanks for the suggestions. Done in the HEAD.

Cheers,
-Larry

**Comment by dpiparo** [comment]
Hi Larry,

this has been merged. Thanks.
I am glad you liked and improved the command line tools!
Another feature which could be very useful for analysis and we did not have the time to properly implement is the ability to "skim" a tree selecting only some branches - if you want a complement to the event selection.
Would you be interested in proposing something in this direction?

Danilo

**Comment by lawrenceleejr** [comment]
Thanks so much for the merge! I agree that this could be really nice feature to have at the command line. It would certainly be straight-forward. When I get another chunk of free time I may look into doing that, sure. If I get around to it, I'll submit another PR. 

Cheers,
-Larry

**Comment by dpiparo** [comment]
Hi Larry,

thanks a lot. I am closing this PR.

Cheers,
    D

**Pull request closed without merging**
