### PR TITLE
[TMVA] Add PyMVA method PyKeras and enable PyMVA specific unit-tests

### PR DESCRIPTION
**Pull request by stwunsch**
Add PyMVA method PyKeras and enable PyMVA specific unit-tests

### CODE REVIEW

**Comment by stwunsch** [comment]
This PR needs a review (mainly because it's a lot of code). Here a small walkthrough:

Preparation:
```
pip install keras theano
```

Testing:
```
# Run unit tests (PyMVA-Keras-Classification and PyMVA-Keras-Regression)
ctest -V -R PyMVA
# Check out examples
cd tutorials/tmva/keras
# Classification
./ClassificationKeras.py
root -l LaunchClasGUI.C
./ApplicationClassificationKeras.py
# Regression
./RegressionKeras.py
root -l LaunchRegGUI.C
./ApplicationRegressionKeras.py
# Multiclass
./MulticlassKeras.py
root -l LaunchMultGUI.py
```

**Comment by stwunsch** [comment]
@lmoneta I've implemented the conditional tests for the keras method. As well, this commit fixes the py2/py3 compatibility issue for the `find_python_module` function in `RootNewMacros.cmake` (simply a py2-only print statement buried in the code).

**Comment by stwunsch** [comment]
Two fixes here:
- `REQUIRED` flag in cmake function `find_python_module` did not work because of wrongly set variable
- If the module is not found, then the function prints the response of the `import <module>` python call

**Comment by stwunsch** [comment]
Now, the verbose reponse of the tests looks like this:

```
test 73
    Start 73: PyMVA-Keras-Classification

73: Test command: /usr/bin/cmake "-DCMD=/usr/users/wunsch/root/build/tmva/pymva/test/testPyKerasClassification" "-DSYS=/usr/users/wunsch/root/build" "-P" "/usr/users/wunsch/root/cmake/modules/RootTestDriver.cmake"
73: Test timeout computed to be: 1500
73: Get test data...
73: Generate keras model...
73: Using Theano backend.
73: Setup TMVA...
73: Using Theano backend.
73: Train model...
73: Run reader and classify 100 events...
73: Mean MVA response on signal: 0.747554
73: Mean MVA response on background: 0.290326
1/2 Test #73: PyMVA-Keras-Classification .......   Passed   14.31 sec
test 74
    Start 74: PyMVA-Keras-Regression

74: Test command: /usr/bin/cmake "-DCMD=/usr/users/wunsch/root/build/tmva/pymva/test/testPyKerasRegression" "-DSYS=/usr/users/wunsch/root/build" "-P" "/usr/users/wunsch/root/cmake/modules/RootTestDriver.cmake"
74: Test timeout computed to be: 1500
74: Get test data...
74: Generate keras model...
74: Using Theano backend.
74: Setup TMVA...
74: Using Theano backend.
74: Train model...
74: Run reader and estimate target of 100 events...
74: Mean squared error: 1.28006
2/2 Test #74: PyMVA-Keras-Regression ...........   Passed   14.53 sec

The following tests passed:
	PyMVA-Keras-Classification
	PyMVA-Keras-Regression

100% tests passed, 0 tests failed out of 2
```

**Comment by lmoneta** [comment]
Thank you Stefan !

 I think everything seems to work fine. Your PR is now ready to be merged 

Cheers

 Lorenzo

**Comment by stwunsch** [comment]
Do you understand why the PR is not marked as solved? I can't see any unmerged commits. I simply closed it by hand.

**Comment by lmoneta** [comment]
On 14 Oct 2016, at 12:03, Stefan Wunsch <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you understand why the PR is not marked as solved? I can't see any unmerged commits. I simply closed it by hand.

Needs to be done by hand, since the merge is not done in github.
Thank you for closing it

 Lorenzo

**Pull request closed without merging**
