### PR TITLE
minimal check if branch name could cause problems

### PR DESCRIPTION
**Pull request by pseyfert**
The idea is to catch branch names, which will lead to problems when using the tree with `Draw` or `MakeClass`.
This can either be the member variables (branch names and `b_`branch names) which have to keep the generated code compilable (and ensure it does what it is expected to do). And the variable names should not lead to confusion with formula evaluation in Draw (e.g. branch names which are pure numbers).

The tests suggested here are:
 * test if branch name is a valid c++ variable name (w/o testing keywords).
 * test if branch name begins with "b_" (potential problem with MakeClass).

on top of that, I also have a [black list](https://github.com/pseyfert/tmva-branch-adder/blob/master/src/blacklist.cpp) of unfortunate branch names: methods of TTrees, which would clash in MakeClass, c++ keywords, variable types, and things TTree::Draw can parse (though I don't see how `TTree::Draw("cos(x)")` would clash with `TTree::Draw("cos")` if there is a variable named `cos`. Because the function `cos` wouldn't work without argument, and the variable `cos` wouldn't work with argument).

I only warn here and don't abort the branch initialisation, not to break third party code (variables with `.` are probably common [e.g. dynamically generated from float](http://lhcb-release-area.web.cern.ch/LHCb-release-area/DOC/davinci/latest_doxygen/d9/d80/_tuple_tool_cone_isolation_8cpp_source.html#l00204) )

Feedback request:
I'm unsure if putting the blacklist into TBranch.cxx is really the best solution to apply here.

### CODE REVIEW

**Comment by dpiparo** [comment]
Hi Paul,
thanks for this nice feature. The problem I may see is that regex are being provided by the STL starting from gcc 4.9.  Did you test with gcc 4.8 too?
Danilo

**Comment by pseyfert** [comment]
Argh, I just ran with gcc 4.8 (4.8.4) and indeed the ROOT build fails (running of hsimple.C results in `terminate called after throwing an instance of 'std::regex_error'`).
I thought regex comes with c++11 and since ROOT anyhow requires c++11 that should be nothing to worry about. Googeling around it seems indeed that regex is only experimental in gcc 4.8.

**Comment by dpiparo** [comment]
Hi Paul,

perhaps it's worth giving a look to TRegexp ?

Danilo

**Comment by pseyfert** [comment]
done

**Comment by dpiparo** [comment]
Merged. Thanks Paul!

**Pull request closed without merging**
