### PR TITLE
fix for "warning: reached end of file while inside a ~~~ block!"

### PR DESCRIPTION
**Pull request by ellert**
The tildes at the beginning and end of a tilde block must be in the same columns.

### CODE REVIEW

**Comment by karies** [comment]
Wow, you're amazing - thanks so much Mattias!

**Comment by couet** [comment]
Many thanks. I ll take care of that

**Comment by ellert** [comment]
Thanks. There was a little glitch and one place was lost in the merging - here is the missing piece:
https://github.com/ellert/root/commit/30cc3546f296e228891f6c9fee55090b73180e84

**Comment by karies** [comment]
Sorry, and thanks for checking! The remaining bit is merged now.

**Pull request closed without merging**
