### PR TITLE
Small clean-up in TSpectrum*

### PR DESCRIPTION
**Pull request by rvernica**
1. Remove unused `SetResolution` function and `fResolution` member from the `TSpectrum*` classes.
2. Update and add references to external documentation, such as the `*.ps.gz` papers and the "manual".

### CODE REVIEW

**Comment by couet** [comment]
Hi,

I see you suppressed all the code related to "fResolution". I agree it might be not used but doing that you changed the calling sequence of some constructors. That will trigger some backward incompatibility. Is it really important for you to clean up it that way ? ... Let us know.

Olivier

**Comment by rvernica** [comment]
I see. I did not realize this might cause issues with backward compatibility.

I did this because of the confusion `TSpectrum(Int_t maxpositions, Double_t resolution=1)` and `SetResolution(Double_t resolution=1)` causes. When you read the documentation, you get the impression that you can set the resolution, which is not true. The only way to figure out this is useless it to search for `fResolution` in the source code.

I can update the patch and leave the function declarations as they are, but make a note in the comments, remove the `fResolution` member, and empty the body of the `SetResolution` function. Let me know.

**Comment by couet** [comment]
One other possibility would be to simply add a comment saying that fResolution is not used right now and  could be used/implemented later.

**Comment by rvernica** [comment]
OK. I will do that and update the patch.

**Comment by rvernica** [comment]
I updated the pull request per your comments.

**Comment by couet** [comment]
Thanks. Update done.

**Comment by rvernica** [comment]
Quick question about the examples in the `TSpectrum` documentation. Most of them reference the `spectra/TSpectrum.root` file ([example](https://github.com/root-mirror/root/blob/1eb2c675f464dbd8c85eaef110961f5fb86bf964/hist/spectrum/src/TSpectrum.cxx#L434)). Is this file available somewhere?

**Comment by rvernica** [comment]
There is a Jira issue about this file https://sft.its.cern.ch/jira/browse/ROOT-6408

**Pull request closed without merging**
