### PR TITLE
PR#1 from fitting parallelization + vectorization

### PR DESCRIPTION
**Pull request by xvallspl**
Template WrappedMultiTF1 keeping backwards compatibility and adding a templated std::function interface for TF1.

This is the first in a series of PR for the integration of the vectorization + parallelization of the fit in ROOT.

### CODE REVIEW

**Comment by peremato** [comment]
@phsft-bot build

**Comment by martinmine** [comment]
@phsft-bot build!

**Comment by martinmine** [comment]
@phsft-bot build!

**Comment by martinmine** [comment]
@phsft-bot build!

**Comment by lmoneta** [comment]
Better maybe to leave the current brace position (less line changed) for the namespace if it is not too much effort, but the important is the 3 spaces indentation and no tabs

**Comment by xvallspl** [comment]
@phsft-bot build!

**Comment by lmoneta** [comment]
This PR can be closed. It is now committed in the ROOT master

**Pull request closed without merging**
