### PR TITLE
interpreter/llvm/Module.mk  -- add extra $ in front of LLVM_FLAGS for osx gcc build

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by gartung** [comment]
@karies please add to v6.02.00-patches and v6.04.00-patches beanches

**Comment by karies** [comment]
Thanks for spotting that! Can you confirm that the master works for you? Then I'll merge into v6-02 and v6-04.

**Comment by gartung** [comment]
Yes the head version on master  works as expected.

**Comment by gartung** [comment]
fixed on master.

**Comment by karies** [comment]
Also applied to v6-04 and v6-02.

**Pull request closed without merging**
