### PR TITLE
Documentation fixes

### PR DESCRIPTION
**Pull request by ellert**
Here are some fixes to the doxygen documentation generation.

### CODE REVIEW

**Comment by couet** [comment]
Hi Mattias, I am trying to take your new filter.cxx but I mac I get:

filter.cxx:233:34: warning: field width should have type 'int', but argument has type 'size_t' (aka 'unsigned long') [-Wformat]
            if (spos) printf("%-*s%s", spos, "///",
                              ~~~^     ~~~~

**Comment by couet** [comment]
The Doxyfile changes you suggest here are done against an old version. In the new one already ignores ClassDef and ClassImp

**Comment by ellert** [comment]
The Doxyfile in master uses:
```
EXCLUDE_SYMBOLS        = *ClassDef* *ClassImp*
MACRO_EXPANSION        = NO
EXPAND_ONLY_PREDEF     = NO
PREDEFINED             = 
```
The Doxyfile in the PR uses
```
EXCLUDE_SYMBOLS        =
MACRO_EXPANSION        = YES
EXPAND_ONLY_PREDEF     = YES
PREDEFINED             = ClassDef(x,y)=// ClassImp(x)=// ClassImpQ(x)=// templateClassImp(x)=// NamespaceImp(x)=//

```

The version in master doesn't really address the problem. At best it can be viewed as a cosmetic change that papers over a tiny fraction of the issues.

If I grep for some common warnings and errors in the logs for the two versions I get:
```
$ grep "Found ';' while" bad.txt | wc -l
89
$ grep "Illegal member name found" bad.txt | wc -l
138
$ grep "no matching file member found for" bad.txt | wc -l
92
$ grep "was not declared or defined" bad.txt | wc -l
185
$ grep "Found ';' while" good.txt | wc -l
1
$ grep "Illegal member name found" good.txt | wc -l
0
$ grep "no matching file member found for" good.txt | wc -l
43
$ grep "was not declared or defined" good.txt | wc -l
41
```
As can be seen the version in master does not work.

**Comment by ellert** [comment]
I added a cast for spos. Thank you for pointing it out.

**Comment by couet** [comment]
I applied the fixes in Doxyfile. Thanks

**Comment by couet** [comment]
In filter.cxx I see that you have suppress le logic (ts) after the comment:

// Inline the directives to show the picture and/or the code

It was suppose to cover the case of both cases of comments:

/*
...
*/

and 

////

I see comments related to that in your PR ... but seems to me both cases still need to be covered... right ?

**Comment by ellert** [comment]
With the new code there is no need to have that logic in two places. The one place where it still is now covers both cases consistently:
```
         size_t l = gLineString.length();
         size_t b = 0;
         do {
            size_t e = gLineString.find('\n', b);
            if (e != string::npos) e++;
            if (spos) printf("%-*s%s", (int) spos, "///",
                              gLineString.substr(b, e - b).c_str());
            else printf("%s", gLineString.substr(b, e - b).c_str());
            b = e;
         } while (b < l);
```
I.e. if the gLineString is modified to contain a linebreak, then when it is printed out it is spiit at the linebreak and the "///" comment marker is added when needed. There is no need to add the comment marker to the gLineString itself.

**Comment by couet** [comment]
Ah yes I understand. Actually it seems to work fine :-). I will do one or two more tests and will commit it.

**Comment by couet** [comment]
New filter.cxx in place.

**Comment by couet** [comment]
All the patches in this PR have been applied. Thanks ! 
I close it.

**Comment by ellert** [comment]
Many thanks for merging the proposed changes. I have made a new PR with the few changes that got lost in the merging.

**Pull request closed without merging**
